modLoader = "javafml"
loaderVersion = "[40,)"
license = "LGPL v3"

[[mods]]
modId = "zytorxlibrary"
version = "1.20.1-0.0.4.1"
displayName = "Zytorx Library"
authors = "Zytorx"
logoFile = "logo.png"
description = '''Just A library mod for everyone to use'''

[[dependencies.zytorxlibrary]]
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[40,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.zytorxlibrary]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"
